# Generated by Django 3.2 on 2021-04-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=500, verbose_name='Название Курса')),
                ('total_count', models.IntegerField(default=0, verbose_name='Количество уроков')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'ПОНЕДЕЛЬНИК'), ('TUESDAY', 'ВТОРНИК'), ('WEDNESDAY', 'СРЕДА'), ('THURSDAY', 'ЧЕТВЕРГ'), ('FRIDAY', 'ПЯТНИЦА'), ('SATURDAY', 'СУББОТА')], max_length=64, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=500, verbose_name='ФИО Студента')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.CharField(max_length=96, verbose_name='Start Hour(s)')),
                ('start_minute', models.CharField(max_length=240, verbose_name='Start Minute(s)')),
                ('end_hour', models.CharField(max_length=96, verbose_name='End Hour(s)')),
                ('end_minute', models.CharField(max_length=240, verbose_name='End Minute(s)')),
                ('day_of_week', models.ManyToManyField(to='teachers.DayOfWeek')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='CourseTimeTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.scheduledtime')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Время урока',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.ManyToManyField(to='teachers.CourseTimeTeacher'),
        ),
    ]
