# Generated by Django 3.2 on 2021-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='teachers.Course'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
