# Generated by Django 3.2 on 2021-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_coursetimeteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.ManyToManyField(related_name='course_time_teacher', to='teachers.CourseTimeTeacher'),
        ),
    ]
