# Generated by Django 3.2 on 2021-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day_of_week',
            field=models.CharField(choices=[('MONDAY', 'ПОНЕДЕЛЬНИК'), ('TUESDAY', 'ВТОРНИК'), ('WEDNESDAY', 'СРЕДА'), ('THURSDAY', 'ЧЕТВЕРГ'), ('FRIDAY', 'ПЯТНИЦА'), ('SATURDAY', 'СУББОТА'), ('SUNDAY', 'ВОСКРЕСЕНЬЕ')], max_length=64, verbose_name='День недели'),
        ),
    ]
